version: '3'

services:
  node:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      # - 80:3000
      - 3000:3000
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=todo_user
      - DATABASE_PASS=An0thrS3crt
      - DATABASE_NAME=todo_db
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=todo_user
      - MYSQL_DATABASE=todo_db
    volumes:
      - ./:/app
    depends_on:
      - mysql


  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret123
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=todo_user
      - MYSQL_DATABASE=todo_db

volumes:
  mysql:
